### ISSUE TITLE
@Objc Support?

### ISSUE THREAD

**Issue by mikemike396** [52inc/SwiftyGiphy#11]
Any plan to support objective c calls into this library? It seems none of the functions are decorated with @objc so you cannot use this library in objective c.

**Comment by brendan09** [comment]
There are currently no plans to add specific objective-c support. Pull requests that don’t fundamentally change the data structures in SwiftyGiphy might be considered, but it’s not generally a priority.

**Comment by mikemike396** [comment]
Understood. I noticed you use structs which are not supported by objc-c. This would require some work to get going in objc-c. 

I will create a swift view controller and link it into my objc-c code.
