### ISSUE TITLE
Cannot inherit from non-open class 'SwiftyGiphyViewController' outside of its defining module

### ISSUE THREAD

**Issue by mikemike396** [52inc/SwiftyGiphy#12]
Getting an error when trying to subclass the Swifty View Controller. Any idea?

<img width="1052" alt="screen shot 2019-01-16 at 12 52 13 pm" src="https://user-images.githubusercontent.com/14999806/51268299-c7855d00-198d-11e9-9ee3-87f12e3a3439.png">

**Comment by brendan09** [comment]
It isn’t designed to be subclassed. It’s recommended to simply present the existing class, similar to using a UIImagePickerController (or similar class).

**Comment by mikemike396** [comment]
Ah okay. Thank you
