### ISSUE TITLE
iOS 13 issues. 

### ISSUE THREAD

**Issue by shial4** [52inc/SwiftyGiphy#17]
Can we get an update here? 
With sub-dependencies update please.

 SwiftyGiphy
 which depends on SDWebImage/GIF was resolved to 4.4.7,
 which depends on SDWebImage/Core (= 4.4.7)

The very old dependencies are blocking our other libraries. Which are breaking under iOS.

**Comment by ulmentflam** [comment]
@shial4 I know you may be using the Giphy developer SDK, but I also just pushed an xcode11 branch that accounts for iOS 13.
