### ISSUE TITLE
Swift 5 Support

### ISSUE THREAD

**Issue by muehlemann** [52inc/SwiftyGiphy#18]
Hello, any plans on adding swift 5 support?

From looking at the code-base I think the only thing that needs to be updated is the podspec.

**Comment by brendan09** [comment]
There is an xcode 11 branch with Swift 5 support. @ulmentflam Do you know when you're going to merge it into master?

**Comment by muehlemann** [comment]
@brendan09  @ulmentflam Any idea when the branch will be merged?

**Comment by ulmentflam** [comment]
@muehlemann Sorry it took me so long, but it was just merged and released a minute ago https://github.com/52inc/SwiftyGiphy/releases/tag/1.3.1
