### ISSUE TITLE
Navigation Bar is hidden when you Push SwiftyGiphyViewController

### ISSUE THREAD

**Issue by ivan-honeycommb** [52inc/SwiftyGiphy#2]
If the pushing view controller has its Navigation Bar Hidden.

The moment you:
let giphy = SwiftyGiphyViewController()
self.navigationController?.pushViewController(giphy, animated: true)

The SwiftyGiphyViewController will inherent the hidden Navigation Bar setting and it will not show the required "Powered by Giphy" Navigation Bar.

This issue happens whenever you are not working with Storyboard, or your views are programatic.

**Comment by brendan09** [comment]
@ivan-honeycommb Thanks for the report. I'll push a fix for it this afternoon, and issue a new version to Cocoapods.

**Comment by brendan09** [comment]
@ivan-honeycommb An update is now out on Cocoapods with a fix for this.

Please 'pod update SwiftyGiphy' to get the latest version, if you're using Cocoapods. Otherwise, the latest is now on master.

**Comment by ivan-honeycommb** [comment]
Thanks Brendan Great job with the framework :)
