### ISSUE TITLE
Can't access frames (array of images)

### ISSUE THREAD

**Issue by kerbelda** [52inc/SwiftyGiphy#7]
Is there a way to access the array of images? Don't see them under GiphyItem or GiphyImageSet.

**Comment by brendan09** [comment]
If you’re accessing the Giphy API, you’ll want to look for responses that have a completion block of GiphyMultipleGIFResponseBlock, which will provide you with a GiphyMultipleGIFResponse.

You can’t access the array of images that view controller has / is managing. But, you can use the giphy API wrapper to query things for your own UI / use. 

Let me know if you have any questions!

**Comment by hollowaytyl** [comment]
Hello my friend, not sure if this answers the question I have, but how do I actually USE this? How do I set an image (gif) after it's selected? What SHOULD I utilize? 

- BitlyGifURL?
- downsizedImage?
- embedURL?
- ???

Is there a simple one-liner comparable to:

imageView.image = giphyImage?

Every thing is pretty straightforward except for what should be done after a collectionView cell is selected. Thank you for any help and tips.

**Comment by brendan09** [comment]
There’s a delegate protocol for you to implement to receive the callback.

**Comment by hollowaytyl** [comment]
Oh wow!!!!!! Thanks!!!!! That helped a lot!!!!!!!!
